version: 2

sources:
  - name: EXPENSE_MANAGEMENT_DB
    database: EXPENSE_MANAGEMENT_DB
    schema: EXPENSE_SCHEMA
    tables:
      - name: CARD_DETAILS
      - name : BANK_DETAILS
      - name : CUSTOMER
      - name : TRANSACTION_DETAILS
      - name : LOCATION
      - name : TAGS
      